### ISSUE TITLE
Cross-linking between rbiorxiv and medrxivr

### ISSUE THREAD

**Issue by mcguinlu** [nicholasmfraser/rbiorxiv#1]
Hi @nicholasmfraser,

I'm the maintainer of [`medrxivr`](https://github.com/ropensci/medrxivr), which provides access to the bioRxiv and medRxiv API's with the aim of allowing transparent and reproducible searching of the records contained in the repositories as part of a systematic review.

I just stumbled across the `rbiorxiv` package this morning, and noticed that it allows for access to the usage reports API endpoint, which is something `medrxivr` doesn't cover.

I was wondering if you would be interested in signposting/cross-linking between the two packages in our respective README's, so that users can find the related package and benefit from the distinct functionality contained in each?

Absolutely no worries if not - just thought I would flag it!

Luke

**Comment by nicholasmfraser** [comment]
Hi @mcguinlu! I have been aware of [`medrxivr`](https://github.com/ropensci/medrxivr) for some time - its a really nice package and certainly a lot more powerful than [`rbiorxiv`](https://github.com/nicholasmfraser/rbiorxiv), which was designed to simply wrap those bioRxiv api endpoints. 

Sure, I'd be more than happy to crosslink between the two packages - although there's some overlap I think both serve a slightly different purpose. I can update the README when I get a chance in the coming days.

FYI, since you mention the usage reports, there is a long-standing error on bioRxiv's side with the annual usage data (e.g. this works for monthly data: https://api.biorxiv.org/usage/m, but this does not work for annual data: https://api.biorxiv.org/usage/y). So the `biorxiv_usage()` function only currently works for the monthly data.

**Comment by mcguinlu** [comment]
Thanks for the kind words - it's been a labour of love, so positive feedback is always nice!

That's great - I'll do the same with the `medrxivr` README this week.

Ah interesting, I hadn't noticed that - the API definitely has some idiosyncrasies, like the fact that you can change the server argument to "medrxiv" not being documented anywhere 🤨
